name: Deploy to github pages
on: 
  push:
    branches: 
      - staging 

jobs: 
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Create Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install Packages and Build Applications
        run: | 
          npm install -g @vue/cli yarn
          yarn install
          yarn build
      - name: Deploy
        uses: s0/git-publish-subdir-action@staging
        env: 
          REPO: self
          BRANCH: master
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

